development:
  adapter: postgresql
  database: tcc_development
  pool: 5
  timeout: 5000
  username: postgres
  password: postgres
  host: localhost

test:
  adapter: postgresql
  database: tcc_test
  pool: 5
  timeout: 5000
  username: postgres
  password: postgres
  host: localhost

production:
  adapter: postgresql
  database: tccr
  database: tcc_production
  pool: 5
  timeout: 5000
  username: postgres
  password: postgres
  host: localhost
